pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3.9'
    }

    environment {
        DOCKER_IMAGE = "RasoolaiahC/demo-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Rasoolaiah-C/demo2.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build') {
    steps {
        sh 'docker build -t RasoolaiahC/demo-app .'
    }
}


        stage('Docker Run') {
            steps {
                // Stop previous container if exists
                sh 'docker rm -f demo-app || true'
                
                // Start new container
                sh 'docker run -d --name demo-app -p 8081:8081 $DOCKER_IMAGE'
            }
        }
    }

    post {
        always {
            echo "Pipeline completed."
        }
    }
}
